#!/usr/bin/env node

/**
 * Generate env-config.js from Netlify environment variables
 *
 * This script runs during Netlify build to inject environment variables
 * into the client-side JavaScript.
 *
 * Usage: node scripts/generate-env.js
 */

const fs = require('fs');
const path = require('path');

// Read environment variables from Netlify
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

// Generate the env-config.js file
const envConfig = `/**
 * Environment Configuration
 *
 * AUTO-GENERATED by scripts/generate-env.js during build
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

window.ENV = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
};


// Development fallback: Check localStorage for testing (NEVER use in production)
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
  const devUrl = localStorage.getItem('DEV_SUPABASE_URL');
  const devKey = localStorage.getItem('DEV_SUPABASE_ANON_KEY');

  if (devUrl && devKey) {
    window.ENV.SUPABASE_URL = devUrl;
    window.ENV.SUPABASE_ANON_KEY = devKey;
  }
}
`;

// Write to env-config.js
const outputPath = path.join(__dirname, '..', 'env-config.js');
fs.writeFileSync(outputPath, envConfig, 'utf8');


if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
}
