#!/bin/bash
# Inject environment variables into env-config.js during Netlify build

echo "🔧 Injecting environment variables into env-config.js..."

cat > env-config.js << 'ENVJS'
/**
 * Environment Configuration
 * AUTO-GENERATED by inject-env.sh during Netlify build
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 */

window.ENV = {
  SUPABASE_URL: '%%SUPABASE_URL%%',
  SUPABASE_ANON_KEY: '%%SUPABASE_ANON_KEY%%'
};

// Development fallback: Check localStorage for testing (localhost only)
if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
  const devUrl = localStorage.getItem('DEV_SUPABASE_URL');
  const devKey = localStorage.getItem('DEV_SUPABASE_ANON_KEY');

  if (devUrl && devKey) {
    console.log('🔧 Using development credentials from localStorage');
    window.ENV.SUPABASE_URL = devUrl;
    window.ENV.SUPABASE_ANON_KEY = devKey;
  }
}

if (window.ENV.SUPABASE_URL && window.ENV.SUPABASE_ANON_KEY) {
  console.log('✅ Environment variables loaded from Netlify build');
} else {
  console.warn('⚠️ Environment variables not set. Using IndexedDB fallback.');
}
ENVJS

# Replace placeholders with actual environment variables
sed -i.bak "s|%%SUPABASE_URL%%|${SUPABASE_URL}|g" env-config.js
sed -i.bak "s|%%SUPABASE_ANON_KEY%%|${SUPABASE_ANON_KEY}|g" env-config.js
rm -f env-config.js.bak

echo "✅ Environment variables injected successfully"
echo "   SUPABASE_URL: ${SUPABASE_URL:0:30}..."
echo "   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:0:30}..."

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "⚠️  WARNING: Some environment variables are missing!"
  echo "   Make sure to set them in Netlify: Settings → Environment variables"
fi
