# Netlify Configuration
# This file configures build settings and redirects for Netlify deployment

[build]
  # Build command (compile Tailwind CSS)
  command = "npm run build"

  # Publish directory (root directory with index.html and pages/)
  publish = "."

  # Functions directory (optional, for serverless functions)
  # functions = "netlify/functions"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirects and rewrites
# Note: The app will auto-redirect to login.html if not authenticated
# No explicit redirect needed here - let the app handle routing

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"

    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"

    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"

    # Content Security Policy (adjust as needed)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://*.supabase.co; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development context (optional)
[context.development]
  command = "npm run build:dev"

[context.deploy-preview]
  command = "npm run build"

[context.production]
  command = "npm run build"
