# Netlify Configuration for MCU Management

[build]
  # No build command needed - static site
  # DISABLED: command = "bash inject-env.sh" (not working, using hardcoded credentials instead)
  # Publish directory is current folder
  publish = "."

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
