# Netlify Configuration for MCU Management

[build]
  # Inject environment variables into env-config.js
  command = "sed -i.bak \"s|\${SUPABASE_URL}|$SUPABASE_URL|g\" env-config.js && sed -i.bak \"s|\${SUPABASE_ANON_KEY}|$SUPABASE_ANON_KEY|g\" env-config.js"
  # Publish directory is current folder
  publish = "."

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
